# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x02\x61\x33\"\xfa\x01\n\x04\x42ook\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\"\n\x05genre\x18\x04 \x01(\x0e\x32\x0e.a3.Book.GenreH\x03\x88\x01\x01\x12\x1a\n\rpublishedYear\x18\x05 \x01(\x05H\x04\x88\x01\x01\"<\n\x05Genre\x12\x0b\n\x07\x46\x41NTASY\x10\x00\x12\t\n\x05SCIFI\x10\x01\x12\x0b\n\x07MYSTERY\x10\x02\x12\x0e\n\nNONFICTION\x10\x03\x42\x07\n\x05_ISBNB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x10\n\x0e_publishedYearb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=19
  _BOOK._serialized_end=269
  _BOOK_GENRE._serialized_start=151
  _BOOK_GENRE._serialized_end=211
# @@protoc_insertion_point(module_scope)
