# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inventoryService.proto\x12\x02\x61\x33\x1a\nbook.proto\"+\n\x11\x43reateBookRequest\x12\x16\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x08.a3.Book\"\"\n\x0f\x43reateBookReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"&\n\x0cGetBookReply\x12\x16\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x08.a3.Book2\x81\x01\n\x10InventoryService\x12:\n\nCreateBook\x12\x15.a3.CreateBookRequest\x1a\x13.a3.CreateBookReply\"\x00\x12\x31\n\x07GetBook\x12\x12.a3.GetBookRequest\x1a\x10.a3.GetBookReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=42
  _CREATEBOOKREQUEST._serialized_end=85
  _CREATEBOOKREPLY._serialized_start=87
  _CREATEBOOKREPLY._serialized_end=121
  _GETBOOKREQUEST._serialized_start=123
  _GETBOOKREQUEST._serialized_end=153
  _GETBOOKREPLY._serialized_start=155
  _GETBOOKREPLY._serialized_end=193
  _INVENTORYSERVICE._serialized_start=196
  _INVENTORYSERVICE._serialized_end=325
# @@protoc_insertion_point(module_scope)
